[2025-09-05T07:54:01.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-05T07:54:01.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: activity.activity_ALL scheduled__2025-09-05T07:53:00+00:00 [queued]>
[2025-09-05T07:54:01.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: activity.activity_ALL scheduled__2025-09-05T07:53:00+00:00 [queued]>
[2025-09-05T07:54:01.988+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 11
[2025-09-05T07:54:02.000+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): activity_ALL> on 2025-09-05 07:53:00+00:00
[2025-09-05T07:54:02.009+0000] {standard_task_runner.py:63} INFO - Started process 3154622 to run task
[2025-09-05T07:54:02.013+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'activity', 'activity_ALL', 'scheduled__2025-09-05T07:53:00+00:00', '--job-id', '111940', '--raw', '--subdir', 'DAGS_FOLDER/dag_activity.py', '--cfg-path', '/tmp/tmp9tt66yqk']
[2025-09-05T07:54:02.017+0000] {standard_task_runner.py:91} INFO - Job 111940: Subtask activity_ALL
[2025-09-05T07:54:02.074+0000] {task_command.py:426} INFO - Running <TaskInstance: activity.activity_ALL scheduled__2025-09-05T07:53:00+00:00 [running]> on host 1877907bc043
[2025-09-05T07:54:02.227+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='activity' AIRFLOW_CTX_TASK_ID='activity_ALL' AIRFLOW_CTX_EXECUTION_DATE='2025-09-05T07:53:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-05T07:53:00+00:00'
[2025-09-05T07:54:02.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-05T07:54:02.260+0000] {activity_ALL.py:17} INFO - Kết nối DB
[2025-09-05T07:54:02.308+0000] {activity_ALL.py:55} ERROR - Lỗi lưu activity_ALL
Traceback (most recent call last):
  File "/opt/airflow/dags/utils/market_data/activity/activity_ALL.py", line 18, in activity_ALL
    df = pd.read_sql('SELECT * FROM "history_data"."eboard_table"', con=enginedb).sort_values(by='symbol',ascending=True)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 6944, in sort_values
    k = self._get_label_or_level_values(by[0], axis=axis)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'symbol'
[2025-09-05T07:54:02.314+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-05T07:54:02.314+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-05T07:54:02.327+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=activity, task_id=activity_ALL, run_id=scheduled__2025-09-05T07:53:00+00:00, execution_date=20250905T075300, start_date=20250905T075401, end_date=20250905T075402
[2025-09-05T07:54:02.385+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-05T07:54:02.400+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
